services:
    ha-sip:
        build:
            context: ./ha-sip
            dockerfile: Dockerfile
            args:
                BUILD_FROM: homeassistant/amd64-base-python
        network_mode: host
        env_file: ./.env