services:
    ha-sip:
        build:
            context: ./ha-sip
            dockerfile: Dockerfile
            args:
                BUILD_FROM: debian:bookworm
        network_mode: host
        env_file: ./.env
