PORT = $PORT
ID_URI = "$ID_URI"
REGISTRAR_URI = "$REGISTRAR_URI"
REALM = "$REALM"
USER_NAME = "$USER_NAME"
PASSWORD = "$PASSWORD"

TTS_PLATFORM = "$TTS_PLATFORM"

HA_BASE_URL = "http://supervisor/core/api"
HA_TOKEN = "$TOKEN"
HA_WEBHOOK_ID = "$HA_WEBHOOK_ID"
