name: Build armv7

on:
  push:
    branches: [ next ]

concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

jobs:
  build-arm:
    runs-on: ubuntu-latest
    environment: next
    strategy:
      matrix:
        architecture: [arm64]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Run build.sh for ARM
        run: |
          export REPO_URL=${{ vars.REPO_URL }}
          export DOCKER_HUB_PASSWORD=${{ secrets.DOCKER_HUB_PASSWORD }}
          ./build.sh build-armv7
